### ISSUE TITLE
Permalink issue

### ISSUE THREAD

**Issue by abhn** [sarmilaupadhyaya/sarmilaupadhyaya.github.io#1]
Hey, nice blog. 

You have a 404 on your homepage. You can either set your site baseurl in the `_config.yml` or not have the additional trailing slash in the url for anchor link (just post.url should work).

here: https://github.com/sarmilaupadhyaya/sarmilaupadhyaya.github.io/blob/cde716d39365494e991f41dee0fd8e713ae63082/index.html#L10
read the docs here: https://jekyllrb.com/docs/posts/#displaying-an-index-of-posts

Cheers and happy hacking!

**Comment by sarmilaupadhyaya** [comment]
Thank you for pointing out.
